
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-wait: 3000
      initial-size: 30
      max-active: 100
#      关闭空闲连接检测间隔，ms
      time-between-eviction-runs-millis: 60000
#      连接最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
#      申请连接时验证可用
      test-on-borrow: true
#      归还连接时验证可用
      test-on-return: false
      connection-properties: ruid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      缓存PSCache，mysql关闭，oracle开启
      pool-prepared-statements: false
      filters: stat,wall
      stat-view-servlet:
        url-pattern: /druid/*
        login-username: seer
        login-password: yuyanjia
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/website/user/user-logout'
        session-stat-max-count: 1000
        session-stat-enable: true
        profile-enable: true
        principal-session-name: USER_SESSION
        url-pattern: /*
        principal-cookie-name: USER_COOKIE
      aop-patterns: site.yuyanjia.template.*,com.github.pagehelper.*
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 2000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
  resources:
      static-locations: file:./static/
  http:
      encoding:
        force: true
        enabled: true
        charset: UTF-8
  pid:
    fail-on-write-error: true
    file: ./application.pid
  quartz:
    job-store-type: jdbc
    # 初始化表
    jdbc:
      initialize-schema: never
server:
  port: 1314
  tomcat:
    uri-encoding: UTF-8
    accesslog:
      enabled: true
  servlet:
    context-path: /template
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    lazy-load-trigger-methods: equals,clone,hashCode,toString
mapper:
  not-empty: false
  identity: MYSQL
  mappers: site.yuyanjia.template.common.util.BaseMapper
pagehelper:
  helper-dialect: mysql
  page-size-zero: true
  reasonable: true
  row-bounds-with-count: true
  support-methods-arguments: true
  params: count=countsql
yuyanjia:
  shiro:
    url-filter-list:
      - /website/user/user-login=anon
      - /website/user/user-logout=logout
      - /website/user/**=authc,perms
      - /**=anon
  filter:
    cors:
      allowed-origin-list:
       - '*'
      allowed-header-list:
       - '*'
      allowed-method-list:
       - POST
       - GET
      exposed-header-list:
       - access-control-allow-headers
       - access-control-allow-methods
       - access-control-allow-origin
       - access-control-max-age
       - X-Frame-Options
      mapping: /website/**
  tomcat:
    connection-timeout: 10000
    acceptor-thread-count: 4
    min-spare-threads: 100
    max-spare-threads: 300
    accept-count: 200
    max-connections: 800
    max-threads: 500
#    protocol: org.apache.coyote.http11.Http11AprProtocol
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      show-details: always
